server:
  port: 8080

spring:
  application:
    name: paymentservice

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
    contexts: dev

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      payments: payments.events
  cache:
    payments-ttl: 30s