server:
  port: 8081

spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:postgresql://localhost:5432/audit
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.yalerikk.common.events"
        spring.json.value.default.type: "dev.yalerikk.common.events.PaymentEvent"

app:
  kafka:
    topics:
      payments: payments.events