server:
  port: 8081

spring:
  application:
    name: audit-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.yalerikk.common.events"
        spring.json.value.default.type: "dev.yalerikk.common.events.PaymentEvent"

app:
  kafka:
    topics:
      payments: payments.events